language: go
go:
- 1.9.x
- 1.10.x

jobs:
  include:
    - stage: Tests
      script:
      - go install ./...
      - go test -v -race ./...
      notifications:
        email: false
      before_install:
      - openssl aes-256-cbc -K $encrypted_f73069fb71a8_key -iv $encrypted_f73069fb71a8_iv
        -in service-account.json.enc -out service-account.json -d
    - stage: Deploy
      deploy:
        provider: gae
        keyfile: service-account.json
        project: timcole-me