language: go
go:
- 1.9.x
- 1.10.x

script:
- go install ./...
- go test -v -race ./...
notifications:
  email: false

jobs:
  include:
  - stage: Deploy to Google App Engine
    language: node_js
    node_js: '10'
    cache:
      yarn: true
    before_install:
      - openssl aes-256-cbc -K $encrypted_f73069fb71a8_key -iv $encrypted_f73069fb71a8_iv -in service-account.json.enc -out service-account.json -d
      - yarn install
      - yarn build
    deploy:
      provider: gae
      keyfile: service-account.json
      project: timcole-me