notifications:
  email: false

jobs:
  include:
  - language: go
    go: 1.9.x
    script:
    - go install ./...
  - language: go
    go: 1.10.x
    script:
    - go install ./...
    - go test -v -race ./...
  - stage: Deploy to Google App Engine
    language: go
    go: 1.10.x
    cache:
      yarn: true
    before_install:
      - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_10.x" | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm i -g yarn
      - openssl aes-256-cbc -K $encrypted_f73069fb71a8_key -iv $encrypted_f73069fb71a8_iv -in service-account.json.enc -out service-account.json -d
    script:
      - yarn install
      - yarn build
    deploy:
      skip_cleanup: true
      provider: gae
      keyfile: service-account.json
      project: timcole-me