runtime: go
api_version: go1.10

env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 0.1
  memory_gb: 0.1
  disk_size_gb: 1

skip_files:
- node_modules/
- frontend/
- .gitignore
- .babeljs
- package.json
- LICENSE
- README.md
- .tasks
- yarn.lock
